name: Deploy to GVS Server

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r web_dashboard/requirements.txt
    
    - name: Run tests
      run: |
        echo "Running basic tests..."
        python -c "import flask; print('Flask import successful')"
        python -c "import pandas; print('Pandas import successful')"
        python -c "import ccxt; print('CCXT import successful')"
    
    - name: Deploy to server
      if: github.ref == 'refs/heads/main'
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd /opt/crypto_trading_system
          git pull origin main
          cd web_dashboard
          source venv/bin/activate
          pip install -r requirements.txt
          sudo systemctl restart crypto-trading
          sudo systemctl status crypto-trading